In [5]:
import numpy as np

In [6]:
GRID_SIZE = 4

In [ ]:
def val_iteration(GAMMA=0.9, non_endpoint_reward=-1):
    # Grid parameters
    ACTIONS = {'UP': 0, 'DOWN': 1, 'LEFT': 2, 'RIGHT': 3}
    TERMINAL_STATES = [0, GRID_SIZE*GRID_SIZE-1]
    THETA = 1e-4

    def get_next_state(state, action):
        row, col = state // GRID_SIZE, state % GRID_SIZE # split into rows & cols -- easier to understand
        if action == ACTIONS['UP']: row = max(0, row - 1)
        elif action == ACTIONS['DOWN']: row = min(GRID_SIZE - 1, row + 1)
        elif action == ACTIONS['LEFT']: col = max(0, col - 1)
        elif action == ACTIONS['RIGHT']: col = min(GRID_SIZE - 1, col + 1)
        return row * GRID_SIZE + col # merge back
    
    # Reward model: Received upon ENTERING next_state
    # Terminal states: R(s') = +10, non-terminal: R(s') = 0
    # V(terminal) = 0 by definition (no future rewards)
    def get_reward(next_state):
        if next_state == 0: return 10
        elif next_state == GRID_SIZE*GRID_SIZE-1: return 10
        else: return non_endpoint_reward
        
    # Initialize value function
    V = np.zeros(GRID_SIZE * GRID_SIZE)

    # Value Iteration
    while True:
        delta = 0
        new_V = V.copy()
        for s in range(len(V)):
            if s in TERMINAL_STATES:
                continue  # Skip terminal states
            max_val = -float('inf')
            for action in ACTIONS.values():
                s_next = get_next_state(s, action)
                reward = get_reward(s_next)
                val = reward + GAMMA * V[s_next]
                if val > max_val:
                    max_val = val
            new_V[s] = max_val
            delta = max(delta, abs(new_V[s] - V[s]))
        V = new_V
        # Display results
        print("Value Function (4x4 Grid):")
        print(V.reshape(GRID_SIZE, GRID_SIZE))
        if delta < THETA:
            break





    # Extract optimal policy
    policy = [None] * (GRID_SIZE * GRID_SIZE)
    for s in range(len(V)):
        if s in TERMINAL_STATES:
            continue
        best_action = None
        best_value = -float('inf')
        for action_name, action_val in ACTIONS.items():
            s_next = get_next_state(s, action_val)
            reward = get_reward(s_next)
            val = reward + GAMMA * V[s_next]
            if val > best_value: # obtain the max
                best_value = val
                best_action = action_name
        policy[s] = best_action

    return V, policy

In [16]:
V1, policy1 = val_iteration(0.5, 0)
print("\nOptimal Policy (Directions):")
print(np.array(policy1).reshape(GRID_SIZE, GRID_SIZE))

Value Function (4x4 Grid):
[[ 0. 10.  0.  0.]
 [10.  0.  0.  0.]
 [ 0.  0.  0. 10.]
 [ 0.  0. 10.  0.]]
Value Function (4x4 Grid):
[[ 0. 10.  5.  0.]
 [10.  5.  0.  5.]
 [ 5.  0.  5. 10.]
 [ 0.  5. 10.  0.]]
Value Function (4x4 Grid):
[[ 0.  10.   5.   2.5]
 [10.   5.   2.5  5. ]
 [ 5.   2.5  5.  10. ]
 [ 2.5  5.  10.   0. ]]
Value Function (4x4 Grid):
[[ 0.  10.   5.   2.5]
 [10.   5.   2.5  5. ]
 [ 5.   2.5  5.  10. ]
 [ 2.5  5.  10.   0. ]]

Optimal Policy (Directions):
[[None 'LEFT' 'LEFT' 'DOWN']
 ['UP' 'UP' 'UP' 'DOWN']
 ['UP' 'UP' 'DOWN' 'DOWN']
 ['UP' 'RIGHT' 'RIGHT' None]]
